### ISSUE TITLE
2段階認証によるログインができない。

### ISSUE THREAD

**Issue by nano4153** [kusamaru/StanDroid#11]
2段階認証しているアカウントでログインしようとすると、以下のエラーが出てきてログインができない。
端末はPixel 6a (Android 14)を使用しています。

お忙しいところ恐れ入りますが、お時間のあるときにご確認して頂けるとありがたいです。

<img width="450"  src="https://github.com/user-attachments/assets/87c93d53-e2cb-4724-ac18-f933904f227c">

**Comment by kusamaru** [comment]
対応版15.6.15-fix1をリリースしました。こちらの環境では動作を確認しましたが念のため暫定版とします。
問題なくログインできるようでしたらお手数ですがIssueのCloseをお願いします。
