### ISSUE TITLE
ログインボタンを押すとクラッシュする

### ISSUE THREAD

**Issue by AQUALaforet** [kusamaru/StanDroid#13]
「ログインが切れました。再ログインしますか？」というポップアップでログインボタンを押すとクラッシュすることがあります。
使用端末はXperia 1 II Android 12です。
クラッシュレポートは以下です。
`androidx.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:124)
androidx.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:119)
com.kusamaru.standroid.nicoapi.login.NicoLogin$secureNicoLogin$2.invokeSuspend(NicoLogin.kt:65)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by kusamaru** [comment]
今回の件はクラッシュレポートから読み解ける範囲に限度がある可能性があるため、もう少し詳細な情報をお願いできますでしょうか。

1. クラッシュの頻度
2. (再現性がある場合)クラッシュを再現するための手順
3. ログインボタンからではなく、メインビューのログインタブからのログインは成功するか

**Comment by AQUALaforet** [comment]
1.クラッシュの頻度
起動直後の生放送のタブで押した場合はクラッシュせず、「ログインできませんでした。」と表示されます。
それ以外のタブに遷移した後に押した場合は必ずクラッシュしました。

2.クラッシュの再現手順
上記の通り、他のタブ(動画、キャッシュ等)に遷移した後に「ログイン」を押すとクラッシュします。

3.メインビューのログインタブでのログイン
何度も正しいか確認しましたが、ログイン不可能でした。(2段階認証を設定しているからでしょうか…)



あと、これらのクラッシュに関係あるかはわかりませんが、起動時に
「問題が発生しました。java.lang.NullpointerException.A...」(この後は見切れており表示できませんでした)と表示されます。

**Comment by kusamaru** [comment]
アップデートのタイミングで内部に保存されていたログイン情報が破損している可能性が考えられます。
暫定版ではありますが、設定の最下部、**開発者用設定**の欄に"ログイン情報のキャッシュを初期化する"機能を追加したバージョン15.6.15-fix3をリリースしました。
こちらでキャッシュを削除の上、もう一度ログインを試行して成功するかをご確認ください。

**Comment by AQUALaforet** [comment]
キャッシュ削除し、再ログインを試みましたがダメでした。
そこで、パスワードに記号が含まれていたのが原因かと思い、記号なしでのパスワードに変更しログインを試みたところ、ログインに成功しました。
記号のあるパスワードだとログインできなかったみたいです。

**Comment by kusamaru** [comment]
ありがとうございます。記号とのことで改めて確認したところ、おそらく内部でのエスケープ処理不足が原因かと思われます。
追って修正版をリリースさせていただきます。
