### ISSUE TITLE
特定の動画でコメントが取得できない。    

### ISSUE THREAD

**Issue by nano4153** [kusamaru/StanDroid#14]
sm7734678のコメントが取得できず、以下のエラーメッセージが表示され、コメントが流れてこない。
端末はPixel 6a (Android 14)を使用しています。

お忙しいところ恐れ入りますが、お時間のあるときにご確認して頂けるとありがたいです。
<img width="450"  src="https://github.com/user-attachments/assets/072c3ec8-d693-4ebf-8fd2-480c214cf5f4">

**Comment by kusamaru** [comment]
修正版をリリースしました。
