### ISSUE TITLE
動画のキャッシュが取得できない。

### ISSUE THREAD

**Issue by smilegold40** [kusamaru/StanDroid#16]
https://ul.h3z.jp/2a92i21J.jpg
キャッシュ取得ボタンを押すと上記のような
エラーメッセージが出ます。
対応よろしくお願いします。

**Comment by kusamaru** [comment]
ニコニコ動画側の仕様変更により全ての動画に暗号化が実施されるようになったためキャッシュ機能のサポートは廃止しました。
今後のアップデートで項目自体の削除を検討していますので、ご了承のほどお願いいたします。

**Comment by smilegold40** [comment]
返信ありがとうございます。
わかりました。
