### ISSUE TITLE
2月20日以降にUPされた動画の読み込みがされません

### ISSUE THREAD

**Issue by rinrin2323** [kusamaru/StanDroid#2]
お世話になっております。

少し前からありがたく使わせて頂いているのですがタイトルの通り最新動画の読み込みで問題が発生しております。

詳しくはわからないのですがおそらく20日前後でニコニコ動画の方で何かが変わってしまったのかと思われます。

普段githubを使ったことがありませんので書き方のテンプレやルール等わからないため、何か不備がございましたら申し訳ありません。

お忙しいとは思いますが、お手すきの際にご確認頂きたく思います。

**Comment by kusamaru** [comment]
本件ですが、ニコニコ側の動画配信サーバーが変更されたことが原因と推測されます。
また、現時点では新サーバーの動画配信APIに関する情報が不十分であり実装が難しいため、対応には時間を要する可能性が極めて高いです。
お手数をおかけしますが、対応まで公式ビューアの利用などをお願いします。

**Comment by Bocchi-Chan2023** [comment]
zenzawatchとhls support(kphrxさんのフォーク)の実装がもしかしたら参考になるかもしれません。

**Comment by kusamaru** [comment]
何故か2/24時点のビルド成果物が実機では正常に動作した(ように見える)ため、ひとまずPre-Releaseとして公開しました。不安定版なので必ずデータベースのバックアップを取ったうえで更新をお願いします。
また、この時点でのソースコードを紛失してしまったため、API仕様の把握及び安定化にはさらに時間が必要となります。申し訳ありませんが今しばらくお待ちください。

**Comment by kusamaru** [comment]
新サーバーに対応した安定版15.6.11を公開しました。更新をお願いします。
