### ISSUE TITLE
キャッシュをダウンロード出来なくなりました。

### ISSUE THREAD

**Issue by kushijunjun** [kusamaru/StanDroid#3]
3月8日現在、昨日時点まで出来ていたキャッシュのダウンロードが出来なくなりました。ニコ動サイドの影響でしょうか。

**Comment by kusamaru** [comment]
ニコニコ動画の新サーバー(domand)では全動画が暗号化HLSによって提供されているため対応予定はありません。加えて、全動画がdomand鯖に移行したためキャッシュダウンロード機能は廃止を予定しています。申し訳ありませんがご了承ください。
