### ISSUE TITLE
帰ってきたニコニコでのニコレポとフォロー新着について

### ISSUE THREAD

**Issue by tomomoto143601** [kusamaru/StanDroid#7]
はじめまして、以前よりこのアプリにはお世話になっております。

タイトルの通りニコニコ動画本家でニコレポが廃止されてフォロー新着に取って代わられてからこのアプリでもニコレポが見れない問題が発生しているように見受けられます。

詳しくはわからないのですがサイバー攻撃後ニコニコ動画本家の方でニコレポが廃止された影響かと思われます。

お忙しい所本当に申し訳ありませんが、お手すきの際にご確認頂きたいと思います。

普段githubを使ったことがなく書き方のテンプレやルール等が分かっておりませんので、何が不備がございましたら申し訳ありません。

既に対応中でしたら行き違いになったことをお詫び申し上げます。

**Comment by kusamaru** [comment]
次回リリースで対応予定です。リリースまで今しばらくお待ち下さい。
リリースの際にこのIssueはCloseさせて頂きます。

**Comment by kusamaru** [comment]
対応版をリリースしました。
